export const GET_RESOURCE          = 'GET_RESOURCE';
export const GET_RESOURCE_FAIL     = 'GET_RESOURCE_FAIL';

export const LIST_RESOURCE         = 'LIST_RESOURCE';
export const ALL_RESOURCE          = 'ALL_RESOURCE';

export const WRITE_PAGINATION      = 'WRITE_PAGINATION';
export const WRITE_STUB            = 'WRITE_STUB';
export const WRITE_RESOURCE        = 'WRITE_RESOURCE';

export const CREATE_RESOURCE = 'CREATE_RESOURCE';
export const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS';
export const CREATE_RESOURCE_FAIL = 'CREATE_RESOURCE_FAIL';

export const DELETE_RESOURCE = 'DELETE_RESOURCE';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_FAIL = 'DELETE_RESOURCE_FAIL';

export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';
export const UPDATE_RESOURCE_SUCCESS = 'UPDATE_RESOURCE_SUCCESS';
export const UPDATE_RESOURCE_FAIL = 'UPDATE_RESOURCE_FAIL';
